export interface Book {
  title: string;
  subtitle?: string;
  url: string;
  image: string;
  rating?: number;
  notes?: string;
  date: Date;
  audiobook?: boolean;
}

export const books: Book[] = [
  {
    title: "The Murder Bot Diaries: Vol 3",
    subtitle: "System collapse",
    url: "https://www.amazon.co.uk/System-Collapse-Murderbot-Diaries-Book-ebook/dp/B0BQGJHG3Q",
    image: "murderbot-system-collapse.webp",
    audiobook: true,
    date: new Date("2025-09-20"),
    rating: 3,
  },
  {
    title: "The Horus Heresy",
    subtitle: "Horus Rising",
    url: "https://www.amazon.co.uk/Horus-Rising-Heresy-Dan-Abnett/dp/184970743X",
    image: "horus-heresy-horus-rising.webp",
    date: new Date("2025-09-18"),
    rating: 5,
  },
  {
    title: "The Murder Bot Diaries: Vol 3",
    subtitle: "Fugitive Telemetry",
    url: "https://www.amazon.co.uk/Fugitive-Telemetry-Murderbot-Diaries-Book-ebook/dp/B088H926KF",
    image: "murderbot-fugitive-telemetry.webp",
    audiobook: true,
    date: new Date("2025-08-24"),
    rating: 4,
  },
  {
    title: "Learning the vi and Vim Editors",
    subtitle: "Power and Agility",
    url: "https://www.amazon.co.uk/Learning-Vim-Editors-Agility-Editing/dp/1492078808",
    date: new Date("2025-08-20"),
    image: "learning-the-vi-and-vim-editors.webp",
    rating: 3,
  },
  {
    title: "tmux 2",
    subtitle: "Productive Mouse-Free Development",
    url: "https://www.amazon.co.uk/Memory-Police-Murderbot-Diaries-Book-ebook/dp/B088H926KF",
    image: "tmux-2.webp",
    date: new Date("2025-08-14"),
    rating: 2,
  },
  {
    title: "The Murder Bot Diaries: Novel",
    subtitle: "Network Effect",
    url: "https://www.amazon.co.uk/Network-Effect-Murderbot-Novel-Diaries/dp/1250229863",
    image: "murderbot-network-effect.webp",
    rating: 4,
    audiobook: true,
    date: new Date("2025-08-10"),
  },
  {
    title: "The Murder Bot Diaries: Vol 2",
    subtitle: "Exit Strategy",
    url: "https://www.amazon.co.uk/Strategy-Murderbot-Diaries-Martha-Wells/dp/1250191858",
    image: "murderbot-exit-strategy.webp",
    rating: 4,
    audiobook: true,
    date: new Date("2025-06-16"),
  },
  {
    title: "Deep Work",
    subtitle: "Rules for Focused Success in a Distracted World",
    url: "https://www.amazon.co.uk/Deep-Work-Focused-Success-Distracted/dp/1455586692",
    image: "deepwork.webp",
    rating: 5,
    date: new Date("2025-05-26"),
  },
  {
    title: "The Murder Bot Diaries: Vol 2",
    subtitle: "Rogue Protocol",
    url: "https://www.amazon.co.uk/Murderbot-Diaries-Vol-Protocol-Strategy/dp/1250389836/261-8914524-1372339",
    image: "murderbot-rogue-protocol.webp",
    audiobook: true,
    date: new Date("2025-05-04"),
    rating: 3,
  },
  {
    title: "The Murder Bot Diaries: Vol 1",
    subtitle: "Artificial Condition",
    url: "https://www.amazon.co.uk/Artificial-Condition-Murderbot-Martha-Wells-ebook/dp/B075DGHHQL",
    image: "murderbot-artificial-condition.webp",
    audiobook: true,
    date: new Date("2025-04-03"),
    rating: 4,
  },
  {
    title: "The Murder Bot Diaries: Vol 1",
    subtitle: "All Systems Red",
    url: "https://www.amazon.co.uk/All-Systems-Red/dp/B076X8K7GX",
    image: "murderbot-all-systems-red.webp",
    audiobook: true,
    date: new Date("2025-03-26"),
    rating: 4,
  },
  {
    title: "The DOSE Effect",
    subtitle: "Small habits to boost brain chemistry",
    url: "https://www.amazon.co.uk/DOSE-Effect-Boosting-Habits-Better/dp/0008667330",
    image: "the-dose-effect.webp",
    audiobook: false,
    date: new Date("2025-03-23"),
    rating: 3,
  },
  {
    title: "Outlive",
    subtitle: " The Science and Art of Longevity",
    url: "https://www.amazon.co.uk/Audible-Outlive-Science-Art-Longevity/dp/B0BTHVPHLJ",
    image: "outlive.webp",
    audiobook: true,
    date: new Date("2025-03-22"),
    rating: 4,
  },
  {
    title: "A Court Of Thorns And Roses",
    url: "https://www.amazon.co.uk/Court-Thorns-Roses/dp/B07955KZ1V",
    image: "a-court-of-thorns-and-roses.webp",
    rating: 4,
    date: new Date("2025-03-10"),
    audiobook: true,
  },
  {
    title: "How to Take Smart Notes in Obsidian",
    url: "https://www.amazon.co.uk/gp/product/B0B9R1BG72",
    image: "how-to-take-smart-notes-in-obsidian.webp",
    rating: 2,
    date: new Date("2025-03-09"),
  },
  {
    title: "Stand Up Straight",
    subtitle: "10 Life Lessons from the Royal Military Academy Sandhurst",
    url: "https://www.amazon.co.uk/gp/product/B0815XPBVD",
    image: "stand-up-straight.webp",
    rating: 4,
    date: new Date("2025-03-08"),
    audiobook: false,
  },
  {
    title: "The Pragmatic Programmer",
    subtitle: "Your Journey to Mastery",
    url: "https://www.amazon.co.uk/gp/product/0135957052",
    image: "the-pragmatic-programmer.webp",
    rating: 5,
    date: new Date("2025-02-13"),
    audiobook: false,
  },
  {
    title: "Digital Minimalism",
    subtitle: "Choosing a Focused Life in a Noisy World",
    url: "https://www.amazon.co.uk/Digital-Minimalism-Living-Better-Technology/dp/0241341132",
    image: "digital-minimalism.webp",
    rating: 4,
    date: new Date("2025-02-27"),
    audiobook: false,
  },
  {
    title: "The Software Engineer's Guidebook",
    subtitle:
      " Navigating senior, tech lead, and staff engineer positions at tech companies and startups",
    url: "https://www.amazon.co.uk/gp/product/B0CV6ZNLLP",
    image: "the-software-engineers-guidebook.webp",
    rating: 4,
    date: new Date("2025-03-04"),
    audiobook: false,
  },
  {
    title: "System Design Inteview",
    subtitle: "An Insider's Guide: Vol 2",
    url: "https://www.amazon.co.uk/gp/product/B0CR977BQH",
    image: "system-design-interview-vol2.webp",
    rating: 4,
    date: new Date("2025-02-27"),
    audiobook: false,
  },
  {
    title: "System Design Inteview",
    subtitle: "An Insider's Guide: Vol 1",
    url: "https://www.amazon.co.uk/System-Design-Interview-Insiders-Guide-ebook/dp/B08B3FWYBX",
    image: "system-design-interview-vol1.webp",
    rating: 5,
    date: new Date("2025-02-27"),
    audiobook: false,
  },
  {
    title: "The hobbit",
    subtitle: "There and back again",
    url: "https://www.amazon.co.uk/Hobbit-J-R-Tolkien/dp/0007458428",
    image: "the-hobbit.webp",
    rating: 4,
    date: new Date("2024-09-20"),
  },
  {
    title: "Tracers in the Dark",
    subtitle: "The Global Hunt for the Crime Lords of Cryptocurrency",
    url: "https://www.amazon.co.uk/Tracers-Dark-Global-Crime-Cryptocurrency/dp/0385548095",
    image: "tracers-in-the-dark.webp",
    rating: 4,
    date: new Date("2023-02-19"),
  },
  {
    title: "Snow Crash",
    url: "https://www.amazon.co.uk/Snow-Crash/dp/B002SPXDZ4",
    image: "snow-crash.webp",
    rating: 5,
    date: new Date("2022-12-21"),
  },
  {
    title: "Sandworm",
    subtitle:
      "A New Era of Cyberwar and the Hunt for the Kremlin's Most Dangerous Hackers",
    url: "https://www.amazon.co.uk/gp/product/B0B9R1BG72",
    image: "sandworm.webp",
    rating: 4,
    date: new Date("2022-11-04"),
  },
  {
    title: "Countdown to Zero Day",
    subtitle: "Stuxnet and the Launch of the World's First Digital Weapon",
    url: "https://www.amazon.co.uk/gp/product/B00KEPLC08",
    image: "countdown-to-zero-day.webp",
    rating: 4,
    date: new Date("2020-03-02"),
  },
  {
    title: "Permanent Record",
    url: "https://www.amazon.co.uk/gp/product/B0B9R1BG72",
    image: "permanent-record.webp",
    rating: 4,
    date: new Date("2020-01-26"),
  },
  {
    title: "Do Androids Dream of Electric Sheep?",
    url: "https://www.amazon.co.uk/Blade-Runner-Originally-published-Androids/dp/B002SQDI3K",
    image: "do-androids-dream-of-electric-sheep.webp",
    rating: 4,
    date: new Date("2023-12-16"),
  },
  {
    title: "Ghost in the Wires",
    subtitle: "My Adventures as the World's Most Wanted Hacker",
    url: "https://www.amazon.co.uk/gp/product/B00FOQS8D6?ie=UTF8&tag=x_gr_bb_amazon-21&linkCode=as2&camp=1634&creative=6738",
    image: "ghost-in-the-wires.webp",
    rating: 3,
    date: new Date("2019-11-08"),
  },
];
